"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# All of the settings below read from environment variables so the same
# codebase can run locally (with safe defaults) and in production (where
# every variable below should be set explicitly). See README.md for the
# exact variables to set when deploying.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-!-@n+6z@9%_rk*rl-wu%r&(7z7pdw&0@yly#+d$l$zs4#becgr',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CORS_ALLOWED_ORIGINS', 'http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # restframework api documentation
    'django.contrib.staticfiles',  # required for serving swagger ui's css/js files
    'drf_yasg',
    # third party apps
    'crispy_forms',
    'crispy_bootstrap4',
    'widget_tweaks',
    'corsheaders',
    # django rest framework and simple jwt
    'rest_framework',
    'rest_framework_simplejwt',
    # django apps
    'account',
    'core',
    # restframework apps
    'api.api_account',
    'api.api_core',
    # staff-only admin panel
    'panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


SIMPLE_JWT = {
    # Short-lived on purpose: if a token leaks, the exposure window is an
    # hour, not a month. Clients are expected to use the refresh token
    # (long-lived, below) to get a new access token instead of staying
    # logged in on one indefinitely.
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=180),
    'ROTATE_REFRESH_TOKENS': False,
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


LOGIN_URL ='login'
LOGOUT_REDIRECT_URL= 'login'
LOGIN_REDIRECT_URL = 'home'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'account.User'

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


STATIC_URL = '/static/'

# Where `collectstatic` gathers files for production (must differ from the
# STATICFILES_DIRS source folder above). Not used by `runserver` locally.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Cache backend, picked with CACHE_BACKEND:
#   redis  -> Redis at REDIS_URL (the `redis` service in docker-compose.yml)
#   file   -> Django's FileBasedCache in CACHE_DIR; shared by every worker
#             process, so this is the one to use on PythonAnywhere
#   db     -> Django's DatabaseCache (run `manage.py createcachetable` once)
#   locmem -> Django's in-process LocMemCache (per process, fine for dev)
#   dummy  -> no caching at all
# Left unset it is "redis" when REDIS_URL is set and "locmem" otherwise, so a
# plain `runserver` needs no setup and Docker picks Redis up automatically.
# All call sites use django.core.cache.cache and never know which it is.
REDIS_URL = os.environ.get('REDIS_URL')
CACHE_BACKEND = (os.environ.get('CACHE_BACKEND') or ('redis' if REDIS_URL else 'locmem')).lower()
CACHE_TIMEOUT = int(os.environ.get('CACHE_TIMEOUT') or 300)

_CACHE_BACKENDS = {
    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL or 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # a Redis outage degrades to "no cache" instead of 500 errors
            'IGNORE_EXCEPTIONS': True,
        },
    },
    'file': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.environ.get('CACHE_DIR') or os.path.join(BASE_DIR, '.cache'),
    },
    'db': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    },
    'locmem': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'adderhub',
    },
    'dummy': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    },
}
if CACHE_BACKEND not in _CACHE_BACKENDS:
    raise ValueError(f'CACHE_BACKEND must be one of {", ".join(_CACHE_BACKENDS)}, not {CACHE_BACKEND!r}')

CACHES = {
    'default': {
        **_CACHE_BACKENDS[CACHE_BACKEND],
        'TIMEOUT': CACHE_TIMEOUT,
        'KEY_PREFIX': 'adderhub',
    }
}
# django_redis logs swallowed errors instead of raising them
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True

STATICFILES_DIRS=[os.path.join(BASE_DIR,"static"),]

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'



# Password-reset mails. Printed to the console unless a real SMTP server is
# configured through the environment.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@adderhub.local')
