# Generated by Django 6.1.1 on 2026-09-14 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_img',
            field=models.ImageField(default='background_images/default.png', help_text='Upload a profile background picture (JPG, JPEG, PNG, GIF only)', upload_to='background_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
