# Generated by Django 6.1.1 on 2026-09-19 04:04

import core.upload
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_img',
            field=models.ImageField(default='background_images/default.png', help_text='Upload a profile background picture (JPG, JPEG, PNG, GIF only)', upload_to=core.upload.UUIDUploadTo('background_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profile_images/default.png', help_text='Upload a profile picture (JPG, JPEG, PNG, GIF only)', upload_to=core.upload.UUIDUploadTo('profile_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
