# Generated by Django 6.1.1 on 2026-09-19 04:04

import core.upload
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options_remove_post_like_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Upload an image (JPG, JPEG, PNG, GIF only)', upload_to=core.upload.UUIDUploadTo('post_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
